# Context
server:
  servlet:
    context-path: /api/v1

# Application
spring:
  application:
    name: InvestmentFunds

  #Database config
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_investment_funds}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
